name: Pruebas TestNG

on: [push, pull_request]

jobs:
build:
runs-on: ubuntu-latest

steps:
- name: Clonar el repositorio
uses: actions/checkout@v3

- name: Instalar Java
uses: actions/setup-java@v3
with:
java-version: '17'
distribution: 'temurin'

- name: Compilar con Maven
run: mvn compile

- name: Ejecutar pruebas con Maven
run: mvn test